version: '3'
services:
  server: 
    build: server/.
    ports:
      - "5000:5000"
    volumes: 
      - ./server/data:/app/data
  client:
    build: client/.
    ports:
      - "9000:80"
  auto-client:
    build: auto-client/.
    ports:
      - "9001:80"